### ISSUE TITLE
Crash upon hitting player with offhand with enchantments

### ISSUE THREAD

**Issue by joshieman06** [joshieman06/gallant-gauntlets#1]
I think it's a compatibility issue. 

Here is the mod list:
```- advancementscreenshot 4.9
	- advancementsfullscreen 1.0
	- architectury 13.0.6
	- autofish 1.0.3
	- automodpack-bootstrap 1.0.0
	- bee_info 1.3
	- cavedust 3.0.0
	- collective 7.84
	- cr-arrows-info 1.2.3+1.21
	- distanthorizons 2.2.1-a
	- entityculling 1.7.0
	- fabric-api 0.104.0+1.21.1
	- fabricloader 0.16.5
	- fastipping 1.0.4
	- forgeconfigapiport 21.1.0
	- guiclock 4.6
	- guicompass 4.8
	- i-see-you-over-there 1.0.2+1.21
	- inmis 2.8.1-1.21.1
	- inmisaddon 1.0.4
	- java 21
	- lightweight-inventory-sorting 1.1.1+1.21
	- minecraft 1.21.1
	- stack-to-nearby-chests 0.5.8
	- additionalstructures 5.0.1-fabric
	- appleskin 3.0.5+mc1.21
	- armadillobrushfix 1.2
	- arts_and_crafts 1.1.8
	- betterarcheology 1.2.0-1.21
	- betterdays 3.1.0.7
	- cardinal-components 6.1.1
	- chunky 1.4.16
	- cloth-config 15.0.130
	- continuity 3.0.0-beta.5+1.21
	- coroutil 1.21.0-1.3.7
	- cosmetic-armor 1.7.0
	- cutthrough 21.1.0
	- dynamiclights 1.8.3+mod
	- entity_model_features 2.2.5
	- entity_pin_cushions 1.0
	- entity_texture_features 6.2.4
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	- fallingleaves 1.16.2
	- fishofthieves 4.0.1
	- foxnap 0.2.0-0-1.21
	- gauntlets 1.1.1
	- geophilic 3.1.1
	- goblinmines_minecart_tweaks 0.1.4
	- guifollowers 3.8
	- handcrafted 4.0.2
	- head_in_the_clouds 1.1.0
	- healingcampfire 6.1
	- horsebuff 2.1.8
	- iris 1.8.0-beta.4+mc1.21.1
	- jade 15.4.1+fabric
	- jei 19.18.3.204
	- leahs-immersive-thunder 1.21+1.2.2
	- lithium 0.13.0
	- mc-258859 1.0
	- mcwlights 1.1.1
	- medievalend 1.0.2
	- modelfix 1.21-1.6
	- modmenu 11.0.2
	- more_armor_trims 1.3.2-1.21
	- morebrushes 1.3
	- mr_better_babies 0.7.13
	- mr_deadly_deadlydungeon 1.0.4
	- mr_developer_resources 1.6.3
	- mr_dungeons_andtaverns 1-v4.3
	- mr_lukis_crazychambers 1.0
	- naturescompass 1.21.1-2.2.5-fabric
	- onlyhammers 1.21.1-0.1
	- owo 0.12.11+1.21
	- particular 1.1.1+1.21
	- persistent_parrots 1.0
	- pets-not-friendly-fire 1.0.1
	- philipsruins 1.21.1
	- placeholder-api 2.4.1+1.21
	- plantsjunk 1.0.1-1.21.1
	- polymorph 1.0.6+1.21.1
	- potioncauldron 1.0.1+mc1.21
	- presencefootsteps 1.10.0+1.21
	- preventaging 1.1
	- progressivearchery 1.2.1-1.21+trinkets
	- puzzleslib 21.1.9
	- randombonemealflowers 4.6
	- resourcefullib 3.0.10
	- respawnablepets 1.21-r1
	- ridehud 1.3.4+1.21
	- rotten_flesh_to_leather 1.0.0
	- simple_baby_zombie_remover 1.0.0
	- skinlayers3d 1.6.6
	- smallships 2.0.0-b1.5
	- sodium 0.6.0-beta.2+mc1.21.1
	- sound_physics_remastered 1.21.1-1.4.6
	- squaremap 1.2.7
	- supermartijn642configlib 1.1.8
	- tectonic 2.4.1a
	- the_bumblezone 7.6.26+1.21.1-fabric
	- thoroughfabric 1.2.2+1.21
	- treeharvester 9.1
	- trimmable_tools 2.0.2
	- trinkets 3.10.0
	- trowel 1.4.0
	- vanilla_degus 1.5.2
	- vanillaconfig 1.2.11+1.21
	- vanillapings 1.10
	- visualoverhaul 5.2.1
	- watut 1.21.0-1.1.3
	- waveycapes 1.4.8
	- youritemsaresafe 4.5
	- zume 1.1.1
```

Here is the obfuscated crash:
```[22:46:50] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3847(net.minecraft.class_5321)" because the return value of "net.minecraft.class_1657.method_5682()" is null
    at joshie.gauntlets.util.GauntletOffhandAttack.offhandAttack(GauntletOffhandAttack.java:191) ~[gauntlets-1.1.1.jar:?]
    at net.minecraft.class_1657.attackOffhand(class_1657.java:13442) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.handler$ccn000$gauntlets$doItemUseMixin(class_310.java:14237) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1583(class_310.java) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1508(class_310.java:2111) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1574(class_310.java:1938) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]```
    
    More testing required

**Comment by Stein-N** [comment]
would it be possible to bundle a zip file with all these mods?

**Comment by joshieman06** [comment]
I will make one today. Hopefully I can also find which mod is incompatible

**Comment by joshieman06** [comment]
Turns out its just a base mod error. No incompatibility

Here is the deobfuscated stack trace:
```java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.getWorld(net.minecraft.registry.RegistryKey)" because the return value of "net.minecraft.entity.player.PlayerEntity.getServer()" is null
	at joshie.gauntlets.util.GauntletOffhandAttack.offhandAttack(GauntletOffhandAttack.java:191)
	at net.minecraft.entity.player.PlayerEntity.attackOffhand(PlayerEntity.java:6942)
	at net.minecraft.client.MinecraftClient.handler$zjo000$gauntlets$doItemUseMixin(MinecraftClient.java:4237)
	at net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient.java)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:2111)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1938)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1246)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```
